# fly launch will fill most fields; minimal stub
app = "eigen-sandbox-service"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
